# numpy


In [1]:
pip install numpy

7.62s - pydevd: Sending message related to process being replaced timed-out after 5 seconds



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [9]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0,4.0,6.0])
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [10]:
A = np.array([[1,2], [3,4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int64


In [11]:
B = np.array([[3,0], [0,6]])
print(A + B)
print(A * B)
             

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]
